Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 20

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Security/Eval:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
