Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Security/Eval:
  Enabled: false

Naming/PredicateName:
  Enabled: false
