name: publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        git remote set-url --push origin https://$USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake deploy_if_needed
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
        GITHUB_TOKEN: ${{secrets.SROIK_GITHUB_TOKEN}}
        USERNAME: ${{secrets.SROIK_USERNAME}}
